spring.application.name=policy_tracker

server.port=${SERVER_PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/policy_tracker_db}

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

jwt.secret=${JWT_SECRET}